### PR TITLE
0.3.5-dev2

### PR DESCRIPTION
**Pull request by hidden4003**

### CODE REVIEW

**Comment by hidden4003** [comment]
Fix #147

**Comment by bigretromike** [comment]
what about favicon ?:P

**Comment by hidden4003** [comment]
what about it ?

**Comment by hidden4003** [comment]
it works on dev server so issue is with the /webui/ in the url and redirect I guess, wasn't my code tho @ElementalCrisis your favicon stuff doesn't work in prod builds, it needs explicit <link rel="icon" in index.ejs

**Pull request merged**
